services:
  nginx:
    image: nginx:latest
    container_name: nginx-router
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - navidrome

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    environment:
      - ND_PORT=4533
    # Add other environment variables as needed
    # volumes:
    #   - ./navidrome/data:/data
    #   - ./navidrome/music:/music
